sylius_resource:
    resources:
        sylius_refund.refund:
            classes:
                model: Sylius\RefundPlugin\Entity\Refund
                factory: Sylius\RefundPlugin\Factory\RefundFactory
        sylius_refund.credit_memo:
            classes:
                model: Sylius\RefundPlugin\Entity\CreditMemo
        sylius_refund.refund_payment:
            classes:
                model: Sylius\RefundPlugin\Entity\RefundPayment

sylius_mailer:
    emails:
        units_refunded:
            subject: Units refunded
            template: "@SyliusRefundPlugin/Email/unitsRefunded.html.twig"

framework:
    messenger:
        buses:
            sylius_refund_plugin.command_bus: ~
            sylius_refund_plugin.event_bus:
                default_middleware: allow_no_handlers

winzou_state_machine:
    sylius_refund_refund_payment:
        class: Sylius\RefundPlugin\Entity\RefundPayment
        property_path: state
        graph: sylius_refund_refund_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            completed: ~
        transitions:
            complete:
                from: [new]
                to: completed
        callbacks:
            after:
                resolve_order_payment_state:
                    on: ['complete']
                    do: ['@Sylius\RefundPlugin\StateResolver\OrderPaymentStateResolver', 'resolve']
                    args: ['object.getOrderNumber()']

sylius_grid:
    templates:
        filter:
            credit_memo_channel: '@SyliusRefundPlugin/Grid/Filter/channel.html.twig'
    grids:
        sylius_refund_credit_memo:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\RefundPlugin\Entity\CreditMemo
            sorting:
                number: asc
            fields:
                number:
                    type: string
                    label: sylius.ui.number
                    sortable: ~
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                channel:
                    type: twig
                    label: sylius.ui.channel
                    options:
                        template: "@SyliusRefundPlugin/Order/Grid/Field/channel.html.twig"
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/total.html.twig"
                issuedAt:
                    type: datetime
                    label: sylius_refund.ui.issued_at
                    options:
                        format: 'Y-m-d H:i:s'
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
                        icon: eye
                        options:
                            link:
                                route: sylius_refund_credit_memo_details
                                parameters:
                                    id: resource.id
                                    orderNumber: resource.orderNumber
                    download:
                        type: default
                        label: sylius_refund.ui.download
                        icon: download
                        options:
                            link:
                                route: sylius_refund_admin_credit_memo_download
                                parameters:
                                    id: resource.id
            filters:
                number:
                    type: string
                    label: sylius.ui.number
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                issuedAt:
                    type: date
                    label: sylius_refund.ui.issued_at
                channel:
                    type: credit_memo_channel
                    label: sylius.ui.channel
        sylius_refund_refund_payment:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\RefundPlugin\Entity\RefundPayment
            sorting:
                orderNumber: asc
            fields:
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                    sortable: ~
                amount:
                    type: twig
                    label: sylius.ui.amount
                    path: .
                    sortable: amount
                    options:
                        template: '@SyliusRefundPlugin/Grid/Field/amount.html.twig'
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: '@SyliusRefundPlugin/Grid/Field/refund_payment_state.html.twig'
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    options:
                        format: 'Y-m-d H:i:s'
                updatedAt:
                    type: datetime
                    label: sylius.ui.updated_at
                    options:
                        format: 'Y-m-d H:i:s'
                actions:
                    type: twig
                    label: sylius.ui.actions
                    path: .
                    options:
                        template: '@SyliusRefundPlugin/Grid/Field/refund_payment_actions.html.twig'
            filters:
                orderNumber:
                    type: string
                    label: sylius_refund.ui.order_number
                createdAt:
                    type: date
                    label: sylius.ui.created_at
                updatedAt:
                    type: date
                    label: sylius.ui.updated_at
